### ISSUE TITLE
how to wire up parts

### ISSUE THREAD

**Issue by flakka2022** [h-RAT/EvilCrowRF_Custom_Firmware_CC1101_FlipperZero#9]
hi , can you pls help me to wire up parts together ? i don't know which pins of esp32 must be connected to cc1101 or Sd adapter and etc.

**Comment by slikkmulah** [comment]
Why dont you just buy an evil crow rf from aliexpress? They're cheap, like $40.

**Comment by sewnbacktogetherwrong** [comment]
My notes from looking at the source code for EvilCrowRFv2:
SD card uses the VSPI interface and IO22 as the SS/CS pin
The CC1101's use HSPI interface
The first CC1101 uses IO pin 5 as SS/CS, and uses IO pin 2 for GDO0 and IO pin 4 for GDO2
The second CC1101 uses IO pin 27 for SS/CS, and uses IO pin 25 for GDO0 and pin 26 for GDO2
The NRF24L01 also uses HSPI, IO pin 15 for SS/CS (and IO pin 33? for data)

**Comment by h-RAT** [comment]
> hi , can you pls help me to wire up parts together ? i don't know which pins of esp32 must be connected to cc1101 or Sd adapter and etc.

Hi, as indicated, use the EvilCrowRF schematic if you want to build your device yourself.

However, you must wire your buttons in the same way as the original device otherwise you will have errors.

The best way is to support the creator by purchasing an original EvilCrowRF.

Join the EvilCrowRF discord for more information

**Comment by flakka2022** [comment]
> Why dont you just buy an evil crow rf from aliexpress? They're cheap, like $40.

i live in Iran so basically i cannot use international services including aliexpress etc.
